### ISSUE TITLE
File downloading is 0 bytes?

### ISSUE THREAD

**Issue by SecretToEveryone** [thomasmichaelwallace/lockepick#13] opened 2021-02-09 00:06 UTC
Hi there, unfortunately after I finish editing and attempt to download, the file is coming out with 0 bytes of data. Am I doing something wrong to cause this?

**Comment by SecretToEveryone** [comment] 2021-02-09 00:22
I've worked out the issue - I don't know how to save my changes after I edit

**Comment by thomasmichaelwallace** [comment] 2021-02-09 09:49
Hey - just to confirm, did you manage to download a file after editing in the end?

**Comment by SecretToEveryone** [comment] 2021-02-09 11:41
> Hey - just to confirm, did you manage to download a file after editing in the end?

I can download a file but it is still blank. Is there a way to save changes? I spent about 30 mins looking earlier but I literally couldn't find it sadly

**Comment by SecretToEveryone** [comment] 2021-02-11 05:43
Also, once this is solved can you please send me a PayPal or something? I
want to pay you for your work on this and making my life easier.

Thanks,
Matt

**Comment by thomasmichaelwallace** [comment] 2021-02-11 10:35
OK -

So I've taken a video of me using the editor, which should help: https://recordit.co/qWXEiDUsGD

The changes 'save' when you press the download button; in that you get a version of the file you uploaded with the changes made. If that's not happening, then we've hit a bug 😄 

I do not know what browser you're using; I test this using Chrome on Windows and Mac. If you're using something different, let me know what so I can take a look.

Also, can you can attach a copy of the file you're trying to edit, I can take a closer look. To do this on github:
 
- Press the [comment] button to start writing a response
- Zip up your save file (or just give it a '.zip' extension, or else github will reject it)
- Drag the file from your computer onto the comment writing area and it should upload it

_n.b. that's very kind of you to offer to pay, but at the moment I do not need the money and my payment was ending up with a tool I could use to smooth my FF6 experience!_

**Comment by SecretToEveryone** [comment] 2021-02-11 12:42
Thanks so much for the prompt response, please find attached. I've tried chrome on two laptops and edge on one. Both were running Windows 10 for reference.
[data.zip](https://github.com/thomasmichaelwallace/lockepick/files/5965225/data.zip)

**Comment by thomasmichaelwallace** [comment] 2021-02-17 11:56
Hmm- this one does have me a little bit stumped, as I _can_ upload, edit, and save this file. I'm going to get a build up with a bit more logging just to see if we can figure this out.

**Comment by DarchangelOmnus** [comment] 2021-02-28 08:19
Had same problem, tried different browsers, tried disabling extensions, looked at the save file code in the src folder, then almost accidentally tried a save where i only changed the gil. Success! So i changed all the values by hand clicked download, Success! It only fails to save a file when i use any of the built in utilities... "set minimum level, 1 of every item" etc.

**Comment by thomasmichaelwallace** [comment] 2021-02-28 19:52
Ahh- that's super useful information, that should help me reproducing so I can take a look at it :)

**Comment by DarchangelOmnus** [comment] 2021-02-28 21:45
yep its awesome was doing a 100% run then went to hospital for 1 month for my son, reformatted forgot to save and was just gonna leave it. saw this tool and thought... hmmm i could be where i was in no time.

**Comment by SecretToEveryone** [comment] 2021-03-04 05:07
This fixed it, thanks so much! I really didn't want to grind out all of Gau's moves haha so thanks so much.

**Comment by thomasmichaelwallace** [comment] 2021-03-04 11:10
I'm just going to reopen to see if I can fix the underlying issue with the utilities :)

**Comment by thomasmichaelwallace** [comment] 2021-03-14 11:59
Just an update-

The issue was specifically with the 'add all items' button (#15), which I've now fixed (you may need to hard refresh the page).

The bug was caused by lack of support for the GBA (Dragons Den) specific ultimate weapons. So if you want to add those, you now can.

**Closed as completed by thomasmichaelwallace** 2021-03-14 11:59 UTC
Labels: question
